#!/usr/bin/env python3
"""
leetr - Leetspeak Translator Tool
Usage: leetr [OPTIONS] <text>
       leetr -s <text>
       leetr -c <text>
"""

import sys
import argparse

__version__ = '1.0.0'
__author__ = '0xAmen'
__github__ = 'https://github.com/MohamedHeniTN'

# Basic leetspeak mappings (simple mode)
BASIC_MAPPINGS = {
    'a': '4',
    'A': '4',
    'e': '3',
    'E': '3',
    'i': '1',
    'I': '1',
    'o': '0',
    'O': '0',
    's': '5',
    'S': '5',
    't': '7',
    'T': '7',
    'g': '9',
    'G': '9',
    ' ': '_'
}

# Comprehensive leetspeak mappings (advanced mode)
# Using raw string literals to avoid escape sequence warnings
COMPREHENSIVE_MAPPINGS = {
    'A': 'Λ',
    'a': '/\\',
    'B': '|3',
    'b': '|3',
    'C': '(',
    'c': '(',
    'D': '[)',
    'd': '[)',
    'E': '☰',
    'e': '€',
    'F': '|=',
    'f': '|=',
    'G': '&',
    'g': '&',
    'H': ']~[',
    'h': ']',
    'I': '!',
    'i': '!',
    'J': '_]',
    'j': '_]',
    'K': '|<',
    'k': '|<',
    'L': '1_',
    'l': '1_',
    'M': r'/\/\[',
    'm': r'/\(\/',
    'N': r'[\]',
    'n': r'[\]',
    'O': '()',
    'o': r'(\/)',
    'P': '|*',
    'p': '|*',
    'Q': '(,)',
    'q': '(,)',
    'R': '|2',
    'r': '|2',
    'S': '5',
    's': '#',
    'T': '7',
    't': '7',
    'U': '(_)',
    'u': '(_)',
    'V': '|V|',
    'v': '|/',
    'W': '|//',
    'w': '|//',
    'X': '><',
    'x': '><',
    'Y': '`/',
    'y': '`/',
    'Z': '2',
    'z': '2',
    ' ': ' /'
}


def translate_basic(text):
    """Translate text to basic leetspeak"""
    result = ""
    for char in text:
        result += BASIC_MAPPINGS.get(char, char)
    # Uppercase the final output for consistency with leetspeak style
    return result.upper()


def translate_comprehensive(text):
    """Translate text to comprehensive leetspeak"""
    result = ""
    for char in text:
        if char in COMPREHENSIVE_MAPPINGS:
            result += COMPREHENSIVE_MAPPINGS[char]
        else:
            result += char
    return result


def main():
    parser = argparse.ArgumentParser(
        description='leetr - Leetspeak Translator Tool',
        epilog='Examples:\n'
               '  leetr Hello World\n'
               '  leetr -s "My name is Test"\n'
               '  leetr -c "Hello World"\n\n'
               f'Created by {__author__}\n'
               f'GitHub: {__github__}\n'
               f'Version: {__version__}',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        '-v',
        '--version',
        action='version',
        version=f'%(prog)s {__version__} - Created by {__author__} - {__github__}'
    )
    
    parser.add_argument(
        'text',
        nargs='+',
        help='Text to translate to leetspeak'
    )
    
    parser.add_argument(
        '-s',
        '--simple',
        action='store_true',
        help='Use simple leetspeak mode (default)'
    )
    
    parser.add_argument(
        '-c',
        '--complex',
        action='store_true',
        help='Use comprehensive/complex leetspeak mode'
    )
    
    args = parser.parse_args()
    
    # Join the text arguments
    input_text = ' '.join(args.text)
    
    # Translate based on mode
    if args.complex:
        output = translate_comprehensive(input_text)
    else:
        output = translate_basic(input_text)
    
    print(output)
    return 0


if __name__ == '__main__':
    sys.exit(main())
